name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install luacheck
        run: sudo apt-get install luarocks && sudo luarocks install luacheck
      - name: Run luacheck
        run: luacheck .
      - name: Install stylua
        run: cargo install stylua
      - name: Run stylua
        run: stylua --check .
